### ISSUE TITLE
 Strong name signature not valid for this assembly FontAwesome.Sharp.dll

### ISSUE THREAD

**Issue by Pherax** [awesome-inc/FontAwesome.Sharp#84]
**Describe the bug**
I am trying to build my first application in visual studio 2022 using c# .net framework. The program runs fine in the IDE but when I publish it to run the .exe i get the following error.

ERROR DETAILS
	Following errors were detected during this operation.
	* [19/01/2022 17:07:04] System.Deployment.Application.InvalidDeploymentException (SignatureValidation)
		- Strong name signature not valid for this assembly FontAwesome.Sharp.dll.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.ComponentVerifier.VerifyStrongNameAssembly(String filePath, AssemblyManifest assemblyManifest)
			at System.Deployment.Application.ComponentVerifier.VerifyComponents()
			at System.Deployment.Application.DownloadManager.DownloadDependencies(SubscriptionState subState, AssemblyManifest deployManifest, AssemblyManifest appManifest, Uri sourceUriBase, String targetDirectory, String group, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)

**Desktop (please complete the following information):**
 - OS: W10
PLATFORM VERSION INFO
	Windows 			: 10.0.19044.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.8.4270.0 built by: NET48REL1LAST_C
	clr.dll 			: 4.8.4420.0 built by: NET48REL1LAST_C
	dfdll.dll 			: 4.8.4270.0 built by: NET48REL1LAST_C
	dfshim.dll 			: 10.0.19041.1 (WinBuild.160101.0800)

**Comment by TapusAggarwal** [comment]
I got the same issue suddenly. 
The way to fix is to uninstall FontAwesome.Sharp and install FontAwesome.Sharp.StrongName

**Comment by mkoertgen** [comment]
Hi @Pherax and @TapusAggarwal ,

Thanks for pointing that out. Strong naming should already have been addressed in 

- https://github.com/awesome-inc/FontAwesome.Sharp/issues/56

Let's have a look about what is missing.

**Comment by mkoertgen** [comment]
Verified current build. Strong name key present & valid

![image](https://user-images.githubusercontent.com/7235760/158059392-a5ccb776-dc7d-4163-ac5d-7a59b2663be7.png)

Verified against the latest package, net48-runtime. Looks good to me as well

![image](https://user-images.githubusercontent.com/7235760/158059478-9457d450-11ac-4ce6-8c86-6e7631d0dc1e.png)

Could you verify using the methods described in
- https://blog.codingoutloud.com/2010/03/13/three-ways-to-tell-whether-an-assembly-dl-is-strong-named/

Is it that in your deployment scenario you probably need a digitally verified signature using
- https://docs.microsoft.com/en-us/windows/win32/seccrypto/using-signtool-to-verify-a-file-signature?redirectedfrom=MSDN

**Comment by FranRDev** [comment]
Hi. I got the same issue.

**Comment by mkoertgen** [comment]
We will add strong name signing in v6+

**Comment by mkoertgen** [comment]
Fixed in 6
